export const browserCoreExamples = [
  "flowhelm browser status",
  "flowhelm browser start",
  "flowhelm browser stop",
  "flowhelm browser tabs",
  "flowhelm browser open https://example.com",
  "flowhelm browser focus abcd1234",
  "flowhelm browser close abcd1234",
  "flowhelm browser screenshot",
  "flowhelm browser screenshot --full-page",
  "flowhelm browser screenshot --ref 12",
  "flowhelm browser snapshot",
  "flowhelm browser snapshot --format aria --limit 200",
  "flowhelm browser snapshot --efficient",
  "flowhelm browser snapshot --labels",
];

export const browserActionExamples = [
  "flowhelm browser navigate https://example.com",
  "flowhelm browser resize 1280 720",
  "flowhelm browser click 12 --double",
  'flowhelm browser type 23 "hello" --submit',
  "flowhelm browser press Enter",
  "flowhelm browser hover 44",
  "flowhelm browser drag 10 11",
  "flowhelm browser select 9 OptionA OptionB",
  "flowhelm browser upload /tmp/flowhelm/uploads/file.pdf",
  'flowhelm browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "flowhelm browser dialog --accept",
  'flowhelm browser wait --text "Done"',
  "flowhelm browser evaluate --fn '(el) => el.textContent' --ref 7",
  "flowhelm browser console --level error",
  "flowhelm browser pdf",
];
