name: FlowHelm
options:
  bundleIdPrefix: ai.flowhelm
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  FlowHelmKit:
    path: ../shared/FlowHelmKit
  Swabble:
    path: ../../Swabble

schemes:
  FlowHelm:
    shared: true
    build:
      targets:
        FlowHelm: all
    test:
      targets:
        - FlowHelmTests

targets:
  FlowHelm:
    type: application
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Sources
    dependencies:
      - target: FlowHelmShareExtension
        embed: true
      - target: FlowHelmWatchApp
      - package: FlowHelmKit
      - package: FlowHelmKit
        product: FlowHelmChatUI
      - package: FlowHelmKit
        product: FlowHelmProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Sources/FlowHelm.entitlements
        CODE_SIGN_STYLE: "$(FLOWHELM_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(FLOWHELM_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(FLOWHELM_APP_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(FLOWHELM_APP_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: FlowHelm
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: ai.flowhelm.ios
            CFBundleURLSchemes:
              - flowhelm
        CFBundleShortVersionString: "2026.2.23"
        CFBundleVersion: "20260223"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - ai.flowhelm.ios.bgrefresh
        NSLocalNetworkUsageDescription: FlowHelm discovers and connects to your FlowHelm gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _flowhelm-gw._tcp
        NSCameraUsageDescription: FlowHelm can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: FlowHelm uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: FlowHelm can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: FlowHelm needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: FlowHelm uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  FlowHelmShareExtension:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: ShareExtension
    dependencies:
      - package: FlowHelmKit
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(FLOWHELM_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(FLOWHELM_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(FLOWHELM_SHARE_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(FLOWHELM_SHARE_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: FlowHelm Share
        CFBundleShortVersionString: "2026.2.23"
        CFBundleVersion: "20260223"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 10
              NSExtensionActivationSupportsMovieWithMaxCount: 1

  FlowHelmWatchApp:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchApp
    dependencies:
      - target: FlowHelmWatchExtension
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(FLOWHELM_WATCH_APP_BUNDLE_ID)"
    info:
      path: WatchApp/Info.plist
      properties:
        CFBundleDisplayName: FlowHelm
        CFBundleShortVersionString: "2026.2.23"
        CFBundleVersion: "20260223"
        WKCompanionAppBundleIdentifier: "$(FLOWHELM_APP_BUNDLE_ID)"
        WKWatchKitApp: true

  FlowHelmWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchExtension/Sources
    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: UserNotifications.framework
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(FLOWHELM_WATCH_EXTENSION_BUNDLE_ID)"
    info:
      path: WatchExtension/Info.plist
      properties:
        CFBundleDisplayName: FlowHelm
        CFBundleShortVersionString: "2026.2.23"
        CFBundleVersion: "20260223"
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: "$(FLOWHELM_WATCH_APP_BUNDLE_ID)"
          NSExtensionPointIdentifier: com.apple.watchkit

  FlowHelmTests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Tests
    dependencies:
      - target: FlowHelm
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(FLOWHELM_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(FLOWHELM_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: ai.flowhelm.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FlowHelm.app/FlowHelm"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: FlowHelmTests
        CFBundleShortVersionString: "2026.2.23"
        CFBundleVersion: "20260223"
