#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${FLOWHELM_INSTALL_E2E_IMAGE:-${FLOWHELM_BOT_INSTALL_E2E_IMAGE:-flowhelm-install-e2e:local}}"
INSTALL_URL="${FLOWHELM_INSTALL_URL:-${FLOWHELM_BOT_INSTALL_URL:-https://flowhelm.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
FLOWHELM_E2E_MODELS="${FLOWHELM_E2E_MODELS:-${FLOWHELM_BOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e FLOWHELM_INSTALL_URL="$INSTALL_URL" \
  -e FLOWHELM_INSTALL_TAG="${FLOWHELM_INSTALL_TAG:-${FLOWHELM_BOT_INSTALL_TAG:-latest}}" \
  -e FLOWHELM_E2E_MODELS="$FLOWHELM_E2E_MODELS" \
  -e FLOWHELM_INSTALL_E2E_PREVIOUS="${FLOWHELM_INSTALL_E2E_PREVIOUS:-${FLOWHELM_BOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e FLOWHELM_INSTALL_E2E_SKIP_PREVIOUS="${FLOWHELM_INSTALL_E2E_SKIP_PREVIOUS:-${FLOWHELM_BOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
